# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  MINVERBUILDMETADATA: build.${{github.run_number}}

jobs:
  build:
    runs-on: [self-hosted,linux,x64]

    steps:
    - uses: actions/checkout@v3
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v3
#      with:
#        dotnet-version: 7.0.x
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}\room6\appsettings.json'
      env:
        GitHub.ClientId: ${{ GH_CLIENTID }}
        GitHub.ClientSecret: ${{ GH_CLIENTSECRET }}
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Build
      working-directory: ./src
      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Publish
      working-directory: ./src
      run: dotnet publish -c Release -o /var/www/room6
    
